### ISSUE TITLE
[Not a bug] Reminder / notes for US phones numbers

### ISSUE THREAD

**Issue by Karmak23** [thibault/libnexmo#1]
Hello Thibault,

on se connait pas mais je lis ton blog. Bref, 3615 ma vie.

À propos de nexmo, je viens de bien galérer avec la lib officielle (j'avais pas connaissance de la tienne…), et juste pour info, pour envoyer des SMS aux US, il faut utiliser une URL rest différente, et mettre en place des choses au préalable directement chez Nexmo (le contenu textuel est pré-paramétré, on ne peut pas envoyer du texte libre).

Concernant l'API, les paramètres sont différents et il ne faut pas urlencoder les numéros de téléphone… Bref c'était la grande joie à découvrir, donc ce ticket est là pour que ça puisse te bénéficier d'une manière ou d'une autre (au moins pour le documenter). 

Le code correspondant, moitié craspouille car pas documenté mais self-lisible j'espère, [est là](https://github.com/Karmak23/libpynexmo/blob/master/nexmomessage/nexmo.py#L44), [et là aussi](https://github.com/Karmak23/libpynexmo/blob/master/nexmomessage/nexmo.py#L183). Ça dépend de la lib `phonenumbers` pour détecter proprement le pays du destinataire et passer d'une URL Nexmo à l'autre à la volée, sans changer l'API d'envoi de SMS.

a+
Olivier

**Comment by thibault** [comment]
Ça marche, merci pour la note.
